### ISSUE TITLE
is there a way to change favicon.ico

### ISSUE THREAD

**Issue by Arconapalus** [minicomp/ed#13]
I'm looking to change the image of favicon.ico but when I do, in staging the image is there but then when I close the bundle jekyll --livereload (terminate) and then reinstate the bundle jekyll --livereload. The favicon.ico erases with original favicon.ico ED. 

Is it possible to have the favicon.ico permanently placed?

**Comment by karlstolley** [comment]
@Arconapalus Jekyll shouldn't be messing with any files in `/assets/` (or any other directory).

Browsers can be weird about caching old favicon files; have you verified your file itself inside of `/assets/` has changed? Or is it the browser that is showing the Ed. favicon?

Do you have a repo with your project?

**Comment by Arconapalus** [comment]
Well inside the file of assets/favicon.ico show ED but I delete that image then save a different image favicon.ico. The only catch here, is that when I stop bundle exec jekyll --livereload and start it again. The image that I recently save is then overwritten by bundle I believe and then the favicon.ico displays ED. 
Thank you for your time

**Comment by Arconapalus** [comment]
Closing as I resolve this. I deleted from dir of file. Then, I erased browser history and the favicon.ico was fixed. 
Thank you for your time
