### ISSUE TITLE
Cannot use it with Jekyll 4

### ISSUE THREAD

**Issue by malcommac** [minicomp/ed#16]
Hi guys, Is there a way to use it in Jekyll 4?

```
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    bundler (~> 1.16)

  Current Bundler version:
    bundler (2.0.2)
This Gemfile requires a different version of Bundler.
Perhaps you need to update Bundler by running `gem install bundler`?
```

**Comment by karlstolley** [comment]
@malcommac we haven't yet rewritten the dependencies for Jekyll 4. However, if you want to try it yourself, in this particular instance, you'll need to install and use the older version of Bundler as listed in the gemfile. Try running:

`$ gem install bundler -v 1.17.3`
`$ bundle _1.17.3_ install`

Note the literal underscores in the `bundle install` command. You need to actually type those (they're not for emphasis here, in other words 😊).
