### ISSUE TITLE
CSS not working

### ISSUE THREAD

**Issue by kHarshit** [minicomp/ed#17]
Hi, the CSS is not working on my github pages using this theme. Please check at https://kharshit.github.io/poems/

Repo URL: https://github.com/kHarshit/poems

**Comment by karlstolley** [comment]
@kHarshit You need to update your `_config.yml` file to point to your `https://kharshit.github.io/` domain and the base URL of `/poems`

**Comment by kHarshit** [comment]
Thanks for your quick response. It works now.
