### ISSUE TITLE
changing the text width in Ed

### ISSUE THREAD

**Issue by chipbrock** [minicomp/ed#3]
I've been trying to change the textwidth of rendered Ed pages without success. The container classes are passed to the theme and seem a logical place to adjust but that doesn't seem to affect the displayed text width. Containers appear in the ed css file as:

/* Slideshow container */
.slideshow-container {
  max-width: 1000;
  position: relative;
  margin: auto;
}

and

/*
 * Container
 *
 * Center the page content.
 */

.container {
/*  max-width: 38rem; */
    max-width: 38rem;
  padding-left:  1rem;
  padding-right: 1rem;
  margin-left:  auto;
  margin-right: auto;
}

@media (min-width: 38em) {
  .container {
    max-width: 32rem;
  }
}
@media (min-width: 56em) {
  .container {
    max-width: 38rem;
  }
}

thanks

**Comment by karlstolley** [comment]
@chipbrock Those are the correct selectors; note that `rem` units are based on the `font-size` specified on `html`, so the `max-width` set there will not always respond to the viewport width, especially on larger screens. To set your own custom, responsive container, you can try striking the `max-width` properties, and setting your own `width` value in percentages.

One other thing to note is that certain browsers, Chrome in particular, are insane in how they cache CSS. Hold down the Shift key as you hit your browser's reload button to make sure you're rendering an up-to-date version of your file (and consider also using a less-cachey development browser, like Firefox Developer Edition).
