### ISSUE TITLE
Not supported warning

### ISSUE THREAD

**Issue by andry-tino** [minicomp/ed#5]
I am trying to use Jekyll in my repository. But everytime I push the site is not built/served correctly and receive this email: 

> The page build completed successfully, but returned the following warning for the `gh-pages` branch:
> You are attempting to use a Jekyll theme, "ed.", which is not supported by GitHub Pages. Please visit https://pages.github.com/themes/ for a list of supported themes. If you are using the "theme" configuration variable for something other than a Jekyll theme, we recommend you rename this variable throughout your site. For more information, see https://help.github.com/articles/adding-a-jekyll-theme-to-your-github-pages-site/.

What is the issue?

**Comment by fn-ix** [comment]
I think the error message is quite clear in this case: _You are attempting to use a Jekyll theme, "ed.", which is not supported by GitHub Pages._ i.e. GitHub Pages only supports a limited number of themes, the list of which you can find here: https://pages.github.com/themes/

You'll have to have one of those, no custom themes allowed!

**Comment by cryptic0** [comment]
Unless you have a specific reason to host github pages, you can always create a droplet on Digitalocean to deploy your site.  It's not free, but not too expensive either.  If it's a low traffic, personal site, the cheapest droplet costs $5 a month.  I am not affiliated with digitalocean in any way.

**Comment by karlstolley** [comment]
@andry-tino if you're still working with this, modify your `_config.yml` file to use the `remote_theme: minicomp/ed` as in this commit https://github.com/minicomp/ed/commit/6727ef69958dbab2e73cd93576f4ccfb16c417e9. Be sure also to comment out or delete the old `theme:` line.
