### ISSUE TITLE
MathJax support

### ISSUE THREAD

**Issue by shoaibkhanz** [minicomp/ed#7]
How to get MathJax working with the blog?

**Comment by shoaibkhanz** [comment]
I got it to work using the following useful link 
`http://dasonk.com/blog/2012/10/09/Using-Jekyll-and-Mathjax`

**Comment by shoaibkhanz** [comment]
`update:` mathjax will work locally but wont on github pages if one uses the http address mentioned in the above link, just add `s` after `http` i.e make it `https` and Mathjax will be rendered without errors.

**Comment by karlstolley** [comment]
@shoaibkhanz Thanks for the update! I'll close this issue out now.

**Comment by yuhouzhou** [comment]
> `update:` mathjax will work locally but wont on github pages if one uses the http address mentioned in the above link, just add `s` after `http` i.e make it `https` and Mathjax will be rendered without errors.



> I got it to work using the following useful link
> `http://dasonk.com/blog/2012/10/09/Using-Jekyll-and-Mathjax`

Would you please help me with this issue? The link you provided has expired. I just created a new issue regarding MathJax https://github.com/minicomp/ed/issues/30
